//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitutionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicMaintenance
    {
        public int MaintenanaceID { get; set; }
        public int PersonID { get; set; }
        public Nullable<bool> PermitForClinicExpansion { get; set; }
        public Nullable<bool> InChargeOfDisabilityAccess { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
