//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitutionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicDoctor()
        {
            this.ClinicPatients = new HashSet<ClinicPatient>();
        }
    
        public int DoctorID { get; set; }
        public int PersonID { get; set; }
        public string BankAccountNumber { get; set; }
        public string Department { get; set; }
        public string WorkShift { get; set; }
        public Nullable<bool> PatientReception { get; set; }
        public Nullable<int> SupervisingManager { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ClinicManager ClinicManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicPatient> ClinicPatients { get; set; }
    }
}
