//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitutionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalInstitution
    {
        public int MedicalInstitutionID { get; set; }
        public string ClinicName { get; set; }
        public Nullable<System.DateTime> MedicalInstitutionConstructionDate { get; set; }
        public string ClinicOwner { get; set; }
        public string ClinicAddress { get; set; }
        public Nullable<int> NumberOfFloors { get; set; }
        public Nullable<int> NumberOfPatientsPerFloor { get; set; }
        public Nullable<bool> HasTerrace { get; set; }
        public Nullable<bool> HasYard { get; set; }
        public Nullable<int> NumberOfAccessPointsForAmbulance { get; set; }
        public Nullable<int> NumberOfDisabledAccessPoints { get; set; }
    }
}
