//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitutionApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalInstitutionDatabaseEntities : DbContext
    {
        public MedicalInstitutionDatabaseEntities()
            : base("name=MedicalInstitutionDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClinicDoctor> ClinicDoctors { get; set; }
        public virtual DbSet<ClinicMaintenance> ClinicMaintenances { get; set; }
        public virtual DbSet<ClinicManager> ClinicManagers { get; set; }
        public virtual DbSet<ClinicPatient> ClinicPatients { get; set; }
        public virtual DbSet<MedicalInstitution> MedicalInstitutions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<vwDoctor> vwDoctors { get; set; }
        public virtual DbSet<vwMaintenance> vwMaintenances { get; set; }
        public virtual DbSet<vwManager> vwManagers { get; set; }
        public virtual DbSet<vwPatient> vwPatients { get; set; }
        public virtual DbSet<ClinicAdministrator> ClinicAdministrators { get; set; }
        public virtual DbSet<vwAdministrator> vwAdministrators { get; set; }
    }
}
