//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitutionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoctor
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Residency { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int DoctorID { get; set; }
        public string BankAccountNumber { get; set; }
        public string Department { get; set; }
        public string WorkShift { get; set; }
        public Nullable<bool> PatientReception { get; set; }
        public Nullable<int> SupervisingManager { get; set; }
    }
}
